version: '3.8'
services:
  neo4j:
    image: neo4j
    container_name: neo4j_db
    ports:
      - "7474:7474"     # HTTP access
      - "7687:7687"     # Bolt protocol
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/test